### Get all books
GET http://localhost:3000/api/books

### Get book by id
GET http://localhost:3000/api/books/10

### Add new book
POST http://localhost:3000/api/books
Content-Type: application/json

{
    "email": "new1@gmail.com",

    "title": "Nowa ksiazka1",
    "author": "Jan Kowalski",
    "year": 2023
}

### Delete book by id
DELETE http://localhost:3000/api/books/13
Content-Type: application/json

{
    "email": "new1@gmail.com"
}