
### Pobierz zamówienia po id użytkownika
GET http://localhost:3003/api/orders/6

### Dodaj nowe zamówienie
POST http://localhost:3003/api/orders/
Content-Type: application/json

{
    "email": "new1@gmail.com",

    "userId": 1,
    "bookId": 14,
    "quantity": 1
}

### Usun zamówienie po id zamówienia
DELETE http://localhost:3003/api/orders/10
Content-Type: application/json

{
    "email": "new1@gmail.com"
}

### Zaktualizuj zamówienie o podanym id zamówienia
PATCH http://localhost:3003/api/orders/2
Content-Type: application/json

{
    "email": "gmail@gmail.com",
    "quantity": 5
}