
### Pobierz orders po id użytkownika
GET http://localhost:3003/api/orders/6

### Dodaj nowa ksiazke
POST http://localhost:3003/api/books
Content-Type: application/json

{
    "email": "gmail@gmail.com",

    "title": "Nowa ksiazka",
    "author": "Jan Kowalski",
    "year": 2023
}

### Usun order po id
DELETE http://localhost:3003/api/orders/1
Content-Type: application/json

{
    "email": "gmail@gmail.com"
}

### Zaktualizuj zamówienie
PATCH http://localhost:3003/api/orders/1
Content-Type: application/json

{
    "email": "gmail@gmail.com",
    "quantity": 10
}